services:
    _defaults:
        autowire: true
        autoconfigure: true

    Mstudio\ContentElement\YoutubeLink:
        tags:
            - { name: contao.content_element, category: media, type: youtube_link }
